export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const DARK_MODE = "DARK_MODE";

export const DROP_IN_PROGRESS = "DROP_IN_PROGRESS";
export const DROP_IN_TODO = "DROP_IN_TODO";


export const ADD_IN_PROGRESS ="ADD_IN_PROGRESS"
export const DROP_IN_DONE = "DROP_IN_DONE"

export const DELETE_TODO_FROM_PROGRESS = "DELETE_TODO_FROM_PROGRESS"
export const DELETE_TODO_FROM_TODO = "DELETE_TODO_FROM_TODO"
export const DELETE_TODO_FROM_DONE = "DELETE_TODO_FROM_DONE"